# Generated by Django 2.2.8 on 2020-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
