# Generated by Django 2.2.8 on 2020-07-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_words_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='words',
            new_name='Word',
        ),
    ]
