# Generated by Django 2.2.8 on 2020-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200719_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
